### ISSUE TITLE
Multi-gang Tuya devices

### ISSUE THREAD

**Issue by Mariano-Github** [kkossev/Hubitat#13]
Hi kkossev, I'm Mariano Colmenarejo

Thanks for sharing your code.

I wanted to tell you about a problem I have with Tuya multi-gang devices.

I have made a Driver Edge (lua) on the smartthings platform for zigbee-multi-switch and I am trying to solve a problem with the new TUYA multi-gang switches, which activate and deactivate all channels at the same time from the app.

I have seen in the code of the DTH zemismart-zigbee-multigang-switch.groovy, that you did the same solution that I also saw in zigbee2mqtt, read all the attributes of the clusters basic in the device configuration. (tuyaBlackMagic)

I have implemented it in my driver just before configuring the clusters on-off and the users are still unable to independently control the different channels.
```
    print("<<< Read Basic cluster attributes >>>")
    device:send(zcl_clusters.Basic.attributes.ManufacturerName:read(device))
    device:send(zcl_clusters.Basic.attributes.ZCLVersion:read(device))
    device:send(zcl_clusters.Basic.attributes.ApplicationVersion:read(device))
    device:send(zcl_clusters.Basic.attributes.ModelIdentifier:read(device))
    device:send(zcl_clusters.Basic.attributes.PowerSource:read(device))
    device:send(cluster_base.read_attribute(device, data_types.ClusterId(0x0000), data_types.AttributeId(0xFFFE)))
```
I don't know if there's something I'm doing wrong or missing, and although I've done some DTH in groovy I'm not an expert either.

The only strange thing I found was the response to cluster E000, attribute D003, which according to Tuya's documentation corresponds to "DP19 Inching switch", data_type Array and the devices respond with a text value "AAAAAgAA" for two gang and "AAAAAgAABAAA" for 3 gang. I don't know if it has anything to do with the problem.

`2022-10-12T16:16:47.916273675+00:00 INFO Zigbee Multi Switch and Child Mc <ZigbeeDevice: 74d8597d-5696-478c-8393-10957ec6cdb8 [0x02E6] (TS0002 Switch)> received Zigbee message: < ZigbeeMessageRx || type: 0x00, < AddressHeader || src_addr: 0x02E6, src_endpoint: 0x01, dest_addr: 0x0000, dest_endpoint: 0x01, profile: 0x0104, cluster: 0xE000 >, lqi: 0x88, rssi: -66, body_length: 0x000F, < ZCLMessageBody || < ZCLHeader || frame_ctrl: 0x08, seqno: 0x08, ZCLCommandId: 0x0A >, < ReportAttribute || < AttributeRecord || AttributeId: 0xD003, DataType: CharString, CharString: “AAAAAgAA” > > > >`

`2022-10-13T23:28:14.636755198+00:00 INFO Zigbee Multi Switch and Child Mc <ZigbeeDevice: 97a3eb51-9928-4894-8b1c-3863b566605a [0x988B] (TS0003 Switch)> received Zigbee message: < ZigbeeMessageRx || type: 0x00, < AddressHeader || src_addr: 0x988B, src_endpoint: 0x01, dest_addr: 0x0000, dest_endpoint: 0x01, profile: 0x0104, cluster: 0xE000 >, lqi: 0xD0, rssi: -48, body_length: 0x0013, < ZCLMessageBody || < ZCLHeader || frame_ctrl: 0x08, seqno: 0xF6, ZCLCommandId: 0x0A >, < ReportAttribute || < AttributeRecord || AttributeId: 0xD003, DataType: CharString, CharString: “AAAAAgAABAAA” > > > >`

Thanks in advance
Cheers

**Comment by kkossev** [comment]
Hi Mariano! 

For the 'TuyaMagic' to work, it is absolutely necessary to send the multiple attributes list in a single command. In your example you are sending the commands one by one, this will not work to unlock the Tuya device. For sure there should be a LUA command that allows reading multiple Zigbee device attributes at once.   
Should be a LUA analog of this Groovy code:

zigbee.readAttribute(0x0000, [0x0004, 0x000, 0x0001, 0x0005, 0x0007, 0xfffe], [:], delay=200)

I just checked [erickv](https://community.smartthings.com/u/erickv) repository [here](https://github.com/erickvneri/erickv-edge-drivers/blob/main/zigbee/button-battery/src/lifecycles/lifecycles.lua) however I don't see the singe Basic cluster read command implemented in that way... So honestly I don't know how Erik's code is working for TS004F scene switch with multiple send_zigbee_message commands, instead of a single one with multiple attributes.

The other important detail for the 'TuyaMagic' to work is to send this command as soon as possible during the Zigbee pairing process. It has no effect on most of the Tuya devices if sent later after the initial pairing process is finished.  So the multiple attributes read command must be the first one to send from the custom driver when the ST hub calls an Initialize (or similar) function.

About the strange data received from cluster E000 attribute D003 - you can simply ignore it in your driver, it seems to be related to some automatic on/off timers used with Tuya SmartLife app.

**Comment by Mariano-Github** [comment]
Good Morning
Thanks for your answer.

Effectively Erickv sends it sequentially since the edge Lua libraries do not have implemented to send the reading and writing of multiple attributes. He worked for smartthings. In the community have been asked to implement it, we'll see when they do it to us.
I've been looking to modify the read attribute library function and implement it in the driver to see if I can.

I have seen that Erick sends it right after sending the binding and configure in his driver.
I was sending it just before in the init lifecycle, just like I saw on your DTH, firts tuyaBlackMagic() and then tuyaBlackMagic()

```
cmds += tuyaBlackMagic()
    //cmds += refresh()
    cmds += zigbee.onOffConfig()
    cmds += zigbee.onOffRefresh()
    sendZigbeeCommands(cmds)
```

I am going to modify it to send it immediately after the binding and configure it as Erick and let them try to see if it works.

Thank you very much for your help, I will keep you updated if it works

**Comment by Mariano-Github** [comment]
Hi,

It seems that it doesn't work for them by sending the attribute reading sequentially.

I asked smartthing when they are going to implement sending multi-attribute read commands.

I tried to modify the read attribute function of the lua library and it doesn't work well.

Thank you

**Comment by kkossev** [comment]
I was 99% sure it will not work if the attributes are read sequentially.

See my TuyaMagic implementation at https://github.com/kkossev/SmartThings/blob/main/PoweredByTuyaTS004F.groovy

The minimum that needs to be implemented in LUA to unlock most of the Tuya devices are the first two commands:

```
"raw 0x0000  {10 00 00 04 00 00 00 01 00 05 00 07 00 FE FF}"
"send 0x${device.deviceNetworkId} 1 1", "delay 200",
```
Is it possible to send these 'raw' Zigbee commands using LUA library functions? 

Regards!

**Comment by Mariano-Github** [comment]
Hi 
It worked!!!

I managed to modify the function to read attributes and send the read in a single command and it was tested by a user and it worked.

`2022-10-21T10:38:49.812858881+00:00 PRINT Zigbee Multi Switch and Child Mc <<< Read Basic clusters attributes >>>
2022-10-21T10:38:49.818767881+00:00 PRINT Zigbee Multi Switch and Child Mc <<<< attr_id >>>> {4, 0, 1, 5, 7, 65534}
2022-10-21T10:38:49.864590548+00:00 INFO Zigbee Multi Switch and Child Mc <ZigbeeDevice: 688e24be-a9cc-4d9f-a7ea-8ce05ecf701b [0x3C41] (Regleta TV Hab. Nuestra)> sending Zigbee message: < ZigbeeMessageTx || Uint16: 0x0000, < AddressHeader || src_addr: 0x0000, src_endpoint: 0x01, dest_addr: 0x3C41, dest_endpoint: 0x01, profile: 0x0104, cluster: Basic >, < ZCLMessageBody || < ZCLHeader || frame_ctrl: 0x00, seqno: 0x00, ZCLCommandId: 0x00 >, < ReadAttribute || AttributeId: 0x0004, AttributeId: 0x0000, AttributeId: 0x0001, AttributeId: 0x0005, AttributeId: 0x0007, AttributeId: 0xFFFE > > >

Device response:

2022-10-21T10:38:50.117413548+00:00 TRACE Zigbee Multi Switch and Child Mc Received event with handler zigbee
2022-10-21T10:38:50.131581214+00:00 INFO Zigbee Multi Switch and Child Mc <ZigbeeDevice: 688e24be-a9cc-4d9f-a7ea-8ce05ecf701b [0x3C41] (Regleta TV Hab. Nuestra)> received Zigbee message: < ZigbeeMessageRx || type: 0x00, < AddressHeader || src_addr: 0x3C41, src_endpoint: 0x01, dest_addr: 0x0000, dest_endpoint: 0x01, profile: 0x0104, cluster: Basic >, lqi: 0xBA, rssi: -82, body_length: 0x0037, < ZCLMessageBody || < ZCLHeader || frame_ctrl: 0x18, seqno: 0x31, ZCLCommandId: 0x01 >, ReadAttributeResponse || < AttributeRecord || AttributeId: 0x0004, ZclStatus: SUCCESS, DataType: CharString, ManufacturerName: “_TZ3000_1obwwnmq” >, < AttributeRecord || AttributeId: 0x0000, ZclStatus: SUCCESS, DataType: Uint8, ZCLVersion: 0x03 >, < AttributeRecord || AttributeId: 0x0001, ZclStatus: SUCCESS, DataType: Uint8, ApplicationVersion: 0x45 >, < AttributeRecord || AttributeId: 0x0005, ZclStatus: SUCCESS, DataType: CharString, ModelIdentifier: “TS011F” >, < AttributeRecord ||
AttributeId: 0x0007, ZclStatus: SUCCESS, DataType: Enum8, PowerSource: PowerSource[SINGLE_PHASE_MAINS] >, < AttributeRecord || AttributeId: 0xFFFE, ZclStatus: SUCCESS, DataType: Enum8, Enum8: 0x00 > > > >`

Thank you very much on behalf of myself and the users for your help, without your help it would not have been possible

**Comment by kkossev** [comment]
You are welcome, Mariano!

**Comment by Mariano-Github** [comment]
If I have any problems with TUYA devices, I will look at your DTH, everyone says that you are an expert in tuya!!

You've been very kind

All the best
