### ISSUE TITLE
Tuya door opener DH for smartthings

### ISSUE THREAD

**Issue by harpreps** [kkossev/Hubitat#19]
Hello,
Can the hubitat handler for Tuya garage door opener be made to work in Smartthings?

**Comment by kkossev** [comment]
hello @harpreps ,

Sorry for noticing your post so late..
The answer is - not directly, as SmartThings have retired the Groovy code.

But I can recommend Wesley Menezes Edge driver : https://community.smartthings.com/t/st-edge-personal-tuya-devices-generic-ef00-device/255270/1
