### ISSUE TITLE
org.codehaus.groovy.runtime.metaclass.MissingMethodExceptionNoStack

### ISSUE THREAD

**Issue by cndjonno** [kkossev/Hubitat#21]
I am getting this error in the hubitat C7 logs for the Tuya Zigbee Metering Plug.

org.codehaus.groovy.runtime.metaclass.MissingMethodExceptionNoStack: No signature of method: user_driver_kkossev_Tuya_Zigbee_Metering_Plug_955.checkPresence() is applicable for argument types: () values: [] (method checkPresence)

![image](https://user-images.githubusercontent.com/43080376/235563069-4e27e180-ecc6-475a-bee2-b68791c92f41.png)

P.S. Thanks for this driver!

**Comment by kkossev** [comment]
Hi,

This is a scheduled job from another driver (Markus's) that has been used with the same device before.
You can get rid of it by clicking on the device web page Initialize button. Then hit F5 to refresh the page and check whether the Preferences are OK for your use (preference values will be set to their defaults).

I can make this happen automatically in the next driver update.
