### ISSUE TITLE
Getting error with Aqara sensor model RTCGQ11LM driver ver 1.2.4

### ISSUE THREAD

**Issue by intra-au** [kkossev/Hubitat#24]
Device manufacturer is empty so the line so SetDeviceName line:if (v.model ==  device.getDataValue('model') && v.manufacturer == device.getDataValue('manufacturer'))  did not work, I've commented out manufacturer part of it and it worked after that.

see log:

[dev:7](http://192.168.0.207/logs?tab=past&deviceId=7#)2023-08-28 13:11:05.170[error](http://192.168.0.207/logs?tab=past&deviceId=7#)java.lang.RuntimeException: java.sql.SQLException: NULL not allowed for column "NAME"; SQL statement:
UPDATE DEVICE SET VERSION = ?, DEVICE_NETWORK_ID = ?, LABEL = ?, NAME = ?, ZIGBEE_ID = ?, DEVICE_TYPE_ID = ?, HT_GROUP_ID = ?, UPDATE_TIME = ?, LAN_ID = ?, DISPLAY_AS_CHILD = ?, MAX_EVENTS = ?, MAX_STATES = ?, DISABLED = ?, MESH_ENABLED = ?, MESH_FULL_SYNC = ?, COLLECTION_ID = ?, SPAMMY_THRESHOLD = ?, COMPATIBLE_DEVICE_ID = ?, PARENT_INSTALLED_APP_ID = ? WHERE ID = ? AND VERSION = ? [23502-214] Query: UPDATE DEVICE SET VERSION = ?, DEVICE_NETWORK_ID = ?, LABEL = ?, NAME = ?, ZIGBEE_ID = ?, DEVICE_TYPE_ID = ?, HT_GROUP_ID = ?, UPDATE_TIME = ?, LAN_ID = ?, DISPLAY_AS_CHILD = ?, MAX_EVENTS = ?, MAX_STATES = ?, DISABLED = ?, MESH_ENABLED = ?, MESH_FULL_SYNC = ?, COLLECTION_ID = ?, SPAMMY_THRESHOLD = ?, COMPATIBLE_DEVICE_ID = ?, PARENT_INSTALLED_APP_ID = ? WHERE ID = ? AND VERSION = ? Parameters: [7, 38B1, Test Sensor, null, 00158D0001E5526E, 603, null, Mon Aug 28 13:11:05 AWST 2023, null, false, 11, 30, false, false, false, 1, 300, null, null, 7, 6] on line 1046 (method parse)
[dev:7](http://192.168.0.207/logs?tab=past&deviceId=7#)2023-08-28 13:11:05.174[info](http://192.168.0.207/logs?tab=past&deviceId=7#)Test Sensor InitializeVars... fullInit = false (driver version 1.2.4 2023/01/26 7:32 PM)
[dev:7](http://192.168.0.207/logs?tab=past&deviceId=7#)2023-08-28 13:11:05.172[info](http://192.168.0.207/logs?tab=past&deviceId=7#)Test Sensor updating the settings from driver version null to 1.2.4 2023/01/26 7:32 PM
[dev:7](http://192.168.0.207/logs?tab=past&deviceId=7#)2023-08-28 13:11:05.167[debug](http://192.168.0.207/logs?tab=past&deviceId=7#)Test Sensor parse: description is read attr - raw: 38B10104060800001801, dni: 38B1, endpoint: 01, cluster: 0406, size: 08, attrId: 0000, encoding: 18, command: 0A, value: 01
[dev:7](http://192.168.0.207/logs?tab=past&deviceId=7#)2023-08-28 13:11:05.083[warn](http://192.168.0.207/logs?tab=past&deviceId=7#)Test Sensor unknown model lumi.sensor_motion.aq2 manufacturer null
[dev:7](http://192.168.0.207/logs?tab=past&deviceId=7#)2023-08-28 13:11:05.073[trace](http://192.168.0.207/logs?tab=past&deviceId=7#)not found!
[dev:7](http://192.168.0.207/logs?tab=past&deviceId=7#)2023-08-28 13:11:05.066[trace](http://192.168.0.207/logs?tab=past&deviceId=7#)GZCGQ11LM:[model:lumi.sen_ill.agl01, manufacturer:LUMI, deviceJoinName:Aqara T1 light intensity sensor GZCGQ11LM]
[dev:7](http://192.168.0.207/logs?tab=past&deviceId=7#)2023-08-28 13:11:05.064[trace](http://192.168.0.207/logs?tab=past&deviceId=7#)GZCGQ01LM:[model:lumi.sen_ill.mgl01, manufacturer:LUMI, deviceJoinName:Mi Light Detection Sensor GZCGQ01LM]
[dev:7](http://192.168.0.207/logs?tab=past&deviceId=7#)2023-08-28 13:11:05.062[trace](http://192.168.0.207/logs?tab=past&deviceId=7#)MCCGQ14LM:[model:lumi.magnet.acn001, manufacturer:LUMI, deviceJoinName:Aqara Contact Sensor MCCGQ14LM]
[dev:7](http://192.168.0.207/logs?tab=past&deviceId=7#)2023-08-28 13:11:05.060[trace](http://192.168.0.207/logs?tab=past&deviceId=7#)RTCGQ11LM:[model:lumi.sensor_motion.aq2, manufacturer:LUMI, deviceJoinName:Xiaomi Motion Sensor RTCGQ11LM]
[dev:7](http://192.168.0.207/logs?tab=past&deviceId=7#)2023-08-28 13:11:05.058[trace](http://192.168.0.207/logs?tab=past&deviceId=7#)RTCGQ15LM:[model:lumi.motion.acn001, manufacturer:LUMI, deviceJoinName:Aqara E1 Motion Sensor RTCGQ15LM]
[dev:7](http://192.168.0.207/logs?tab=past&deviceId=7#)2023-08-28 13:11:05.056[trace](http://192.168.0.207/logs?tab=past&deviceId=7#)RTCGQ12LM:[model:lumi.motion.agl02, manufacturer:LUMI, deviceJoinName:Aqara T1 Motion Sensor RTCGQ12LM]
[dev:7](http://192.168.0.207/logs?tab=past&deviceId=7#)2023-08-28 13:11:05.053[trace](http://192.168.0.207/logs?tab=past&deviceId=7#)RTCGQ13LM:[model:lumi.motion.agl04, manufacturer:LUMI, deviceJoinName:Aqara High Precision Motion Sensor RTCGQ13LM, motionRetriggerInterval:[min:2, scale:0, max:200, step:1, type:number], motionSensitivity:[min:1, scale:0, max:3, step:1, type:number, options:[1:low, 2:medium, 3:high]]]
[dev:7](http://192.168.0.207/logs?tab=past&deviceId=7#)2023-08-28 13:11:05.050[trace](http://192.168.0.207/logs?tab=past&deviceId=7#)RTCGQ14LM:[model:lumi.motion.ac02, manufacturer:LUMI, deviceJoinName:Aqara P1 Motion Sensor RTCGQ14LM, motionRetriggerInterval:[min:2, scale:0, max:200, step:1, type:number], motionSensitivity:[min:1, scale:0, max:3, step:1, type:number, options:[1:low, 2:medium, 3:high]]]
[dev:7](http://192.168.0.207/logs?tab=past&deviceId=7#)2023-08-28 13:11:04.910[trace](http://192.168.0.207/logs?tab=past&deviceId=7#)RTCZCGQ11LM:[model:lumi.motion.ac01, manufacturer:aqara, deviceJoinName:Aqara FP1 Human Presence Detector RTCZCGQ11LM, capabilities:[motionSensor:true, temperatureMeasurement:true, battery:true, powerSource:true, signalStrength:true], attributes:[presence, presence_type], preferences:[motionSensitivity:[min:1, scale:0, max:3, step:1, type:number, options:[1:low, 2:medium, 3:high]], approachDistance:true, monitoringMode:true, sendBatteryEventsForDCdevices:true], motionRetriggerInterval:[min:2, scale:0, max:200, step:1, type:number]]
[dev:7](http://192.168.0.207/logs?tab=past&deviceId=7#)2023-08-28 13:11:04.898[info](http://192.168.0.207/logs?tab=past&deviceId=7#)Test Sensor InitializeVars... fullInit = false (driver version 1.2.4 2023/01/26 7:32 PM)
[dev:7](http://192.168.0.207/logs?tab=past&deviceId=7#)2023-08-28 13:11:04.890[info](http://192.168.0.207/logs?tab=past&deviceId=7#)Test Sensor updating the settings from driver version null to 1.2.4 2023/01/26 7:32 PM
[dev:7](http://192.168.0.207/logs?tab=past&deviceId=7#)2023-08-28 13:11:04.883[debug](http://192.168.0.207/logs?tab=past&deviceId=7#)Test Sensor parse: description is read attr - raw: 38B10104000A0000210000, dni: 38B1, endpoint: 01, cluster: 0400, size: 0A, attrId: 0000, encoding: 21, command: 0A, value: 0000

**Comment by kkossev** [comment]
Sorry for the very late reply... This is fixed in the development branch version.
