### ISSUE TITLE
When in Scene mode, TS004F broadcasts the button-press events, instead of unicast to Hubitat Elevation Zigbee coordinator.

### ISSUE THREAD

**Issue by kkossev** [kkossev/Hubitat#3]
Main issue: When in Scene mode, TS004F broadcasts the button-press events, instead of unicast to HE ZIgbee cordinator.

**Comment by kkossev** [comment]
Hubitat Elevation platform-specific, nothing can be done from the driver side... Closed.

**Comment by MattWestb** [comment]
Can HA forcing sending dealt response to no ZCL commands ?
The Zigbee stack is sending default response to all ZCL commands if the flag in the frame is not set (flag name = disable default response),
ZHA can doing that and is being used for all TS004X plus the DP / MCU devices (TS0601) and some more devices that  is using no standard cluster / commands / attributes for not getting repeated frames from the devices.
If can getting the system sending it is the switch not blocked re sending commands and is working faster the sending more commands fast.

By the way great work done !!
